apiVersion: v1
kind: Service
metadata:
  name: mybackendlb-node-port

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30004

  selector:
    component: backend
    app: my-app